/* labgen.c -- this file is part of C Ratfor.
 * Copyright (C) 2009, 2010 Stefano Lattarini <stefano.lattarini@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "rat4-common.h"
#include "labgen.h"

static int startlab; /* first label used by `labgen()' */
static int label; /* next label returned by generate_labels */

/* labgen - generate n consecutive labels, return first one */
int
labgen(int n)
{
    int olabel = label;
    label += n;
    return(olabel);
}

/* set_starting_label - set starting label and nex label to lab */
int
set_starting_label(int lab)
{
    label = startlab = lab;
    return(label);
}


/* can_label_conflict - tell if user label lab can conflict with labels
 *                      generated by ratfor
 */
bool
can_label_conflict(int lab)
{
    return(lab >= startlab? true : false);
}

/* vim: set ft=c ts=4 sw=4 et : */
