#include "rat4-common.h"
#include "labgen.h"

static int startlab; /* first label used by `labgen()' */
static int label; /* next label returned by generate_labels */

BEGIN_C_DECLS

/* labgen - generate n consecutive labels, return first one */
int
labgen(int n)
{
    int olabel = label;
    label += n;
    return(olabel);
}

/* set_starting_label - set starting label and nex label to lab */
int
set_starting_label(int lab)
{
    label = startlab = lab;
    return(label);
}


/* can_label_conflict - tell if user label lab can conflict with labels
 *                      generated by ratfor
 */
bool
can_label_conflict(int lab)
{
    return(lab >= startlab? true : false);
}

END_C_DECLS

/* vim: set ft=c ts=4 sw=4 et : */
